name: "Deploy site"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
  workflow_dispatch:
    # Allow manually running workflow
  schedule:
    - cron: "23 2 * * *"

env:
  DEPLOY: >-
    ${{
    github.event_name != 'pull_request'
    &&
    github.ref == 'refs/heads/master'
    }}
  OUTPUT: _html

jobs:
  build:
    name: Build lektor website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Install Imagemagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.4"

      - run: uv run python --version
      - name: Build lektor website
        run: uv run lektor build -f webpack -O '${{ env.OUTPUT }}'

      - name: Check for broken internal links
        uses: wjdp/htmltest-action@master
        with:
          path: ${{ env.OUTPUT }}
          config: .htmltest.yml
          skip_external: true
          log_level: 1

      - name: Deploy lektor website
        if: env.DEPLOY == 'true'
        run: lektor deploy -O '${{ env.OUTPUT }}' ghpages-https
        env:
          LEKTOR_DEPLOY_USERNAME: lektor
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
